[package]
name = "algorithms"
version = "0.1.1"
authors = ["schulke-214 <schulkemaximilian@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
uuid = { version = "0.8", features = ["serde", "v4"] }